export type ErrorCode =
  | "QTY_EXCEEDS_AVAILABLE"
  | "INVALID_STORAGE_LOCATION"
  | "WAREHOUSE_MISMATCH"
  | "NO_ACTIVE_TRANSFER_SESSION"
  | "SESSION_NOT_FOUND"
  | "SESSION_NOT_OWNED"
  | "SESSION_NOT_ACTIVE"
  | "USER_LOCATION_NOT_FOUND"
  | "PRODUCT_NOT_FOUND"
  | "NO_LINES_IN_USER_LOCATION"
  | "QTY_EXCEEDS_PENDING_IN_HAND"
  | "QTY_NOT_FULFILLED"
  | "SERVER_ERROR";


  